receivers:
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      paging:
  filelog:
    include:
      - /fake_log.log

exporters:
  otlp:
    endpoint: "debian2:4317"
    tls:
      insecure: false
      ca_file: /ca.crt
      cert_file: /client.crt
      key_file: /client.key

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [otlp]
    logs:
      receivers: [filelog]
      exporters: [otlp]
