services:
  debian1:
    build:
      context: ./debian1
      dockerfile: Dockerfile
    container_name: debian1
    volumes:
      - ./debian1/config.yaml:/etc/otelcol/config.yaml

  debian2:
    build:
      context: ./debian2
      dockerfile: Dockerfile
    container_name: debian2
    environment:
      - OTEL_LOG_LEVEL=trace
    ports:
      - 127.0.0.1:4317:4317
    volumes:
      - ./debian2/config.yaml:/etc/otelcol/config.yaml
      - ./debian2/out.json:/out.json

  prometheus:
    image: docker.io/prom/prometheus:v3.2.1
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: docker.io/grafana/loki:2.9.13
    container_name: loki
    volumes:
      - ./loki/data:/loki
      - ./loki/config.yml:/etc/loki/local_config.yaml

  grafana:
    image: docker.io/grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    depends_on:
      - loki

  logstash:
    image: docker.io/logstash:8.17.3
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/logstash.yml:/usr/share/logstash/logstash.yml
      - ./logstash/out.json:/var/log/logstash/out.json
